### ISSUE TITLE
Enhancement? add a HV version of advanced furnace?

### ISSUE THREAD

**Issue by DoomSquirter** [CD4017BE/InductiveAutomation#18]
I'm either doing something horribly wrong (which I probably am) but I need to make a metric ton of Quantum Integrated Ingots and each one takes about 20+ minutes to process in the advanced furnace.  Would be nice to have a HV version to speed up the process?  It's that last part in the Advanced furnace that seems to be the sticking point for making them.  The voltage bar is almost at zero the entire time and I have it on a dedicated energy link feeding it as much power as it can handle.

Latest version 1.10.2

Side note: is there a layman's viewpoint/doc regarding when to use/not use the working resistance slider on machines?  I haven't taken electronics since high school and that was 30+ years ago lol  The pdf was informative but mostly over my head for the most part.  

Thanks for a very interesting mod.  I'm finding a ton of utility with it thus far.

**Comment by CD4017BE** [comment]
The Advanced furnace should be able to run much faster and have a full power bar. So you've either set a too high resistance (always use lowest possible (5 Ohm) unless you are running out of power), or you set a too low voltage in the EnergyLink: when used as power supply, set it to about 60-80% the maximum voltage of the machines and cables you are using (so probably 800-1000V). And check, if you have any low voltage cables or machines connected because they would just burn all the power above their limit (I was so friendly to not making them explode).

Generally to make things work at all: maxVoltage >= supplyVoltage > storageVoltage > consumerVoltage >= 0V. And for best operation speed: supply Voltage as high as possible and consumer Resistance & Voltage as low as possible (as long as the machines allow you to manually set).

I should probably add this information to the manual as like you said "layman's viewpoint"

**Comment by DoomSquirter** [comment]
machine is set to 5, energy link is set to 1200(umax) 1190 (umin).  using conductive alloy wire.  there is only the advanced furnace and the electromagnetic compression assembler on the same circuit, also set to 5.  

using rftools batteries to push power into energy link

I've got another very long run from another energy link doing all the preliminary work to make the gasses, etc to get to this point and none of the machines have had any issues whatsoever and all work with full green in power bar, which is why I filed this issue.  Same setups yet this one process/machine seems to be having an issue with the high amount of voltage needed for being a MV type machine or something.  I've used the advanced furnace previously to make some other things and didn't have this issue at all.  It's just these ingots.

Glad to see my guesses were pretty spot on tho about what to do with the settings tho, so I can guess you made the mod somewhat intuitive and no extreme technical know-how is needed lol.  If you could try it yourself in 1.10.2 I'd appreciate it.  I'll redo the setup again to see if there is something I missed but I really don't think I have missed anything.

**Comment by DoomSquirter** [comment]
just fyi, I redid setup, no change.  I did it this time with superconductive wire still running from the non hv energy link.  Getting 0.5 kW @ 10A with no bars at all on that machine while processing those ingots

as a comparison, in other line, one of my decompression coolers is running at 280kW @ ~230A.   not having issues supplying power whatsoever, for everything but those quantum ingots.

**Comment by CD4017BE** [comment]
500W / 10A = 50V = 10A \* 5Ohm so your machine is definitely only getting 50V and not 1200V. So check the voltages on all machines and cables using the Volt Meter. Also check if cables and/or machines are connected in circles, because it seems that in that case the energy transfer algorithm sometimes doesn't spread the power correctly through the cables. Just remove any unnecessary cable connections via sneak right click or in the machine's energy-side-config tab.

**Comment by DoomSquirter** [comment]
I apologize for wasting ur time.  I had rewired but not replaced machines.  For some reason when I picked and replaced machine back, it started going faster.  Should have done that first.  Now it's got full power and doing the process quite happilly.  No clue, but thanks alot.  will close the issue.
