### ISSUE TITLE
Steam compression assembler doesn't work

### ISSUE THREAD

**Issue by th4umiel** [CD4017BE/InductiveAutomation#22]
As the title says, I have it in my survival world, but the same happens when I made tests in creative. Its electromagnetic counterpart works fine.
For "doesn't work" I mean that:
1. It doesn't execute any recipe;
2. I can't place items in its GUI except with item pipes (strange...).
I've a water source, a steam boiler directly connected to the compression assembler, the assembler has steam and pressure but it does nothing.

**Comment by CJL48** [comment]
I've also had this problem, on an instance using CD401Lib 4.3.3, IA 5.3.1, and Forge 1.10.2-12.18.2.2122. I hadn't reported it yet because the instance has 90+ mods, so I wasn't sure that it wasn't a mod interaction.

**Comment by th4umiel** [comment]
Yes the situation it's the same for me, 101 mods, forge 1.10.2-12.18.2.2120 and latest version of the lib and the mod.

EDIT: The assembler works when I close and re-open the save, but obviously this remains quite a bug :(

**Comment by CD4017BE** [comment]
From v4.2 to v4.3 (v5.2 to v5.3 for IA) I rewrote almost my entire template and api system and did a some code editing with search and replace using regular expressions. I just checked the code again and it seems that I accidentally replaced the ingredient slots of that machine with extract only slots instead of normal IItemHandler slots.

**Comment by th4umiel** [comment]
Thanks for your quick answer!
